### ISSUE TITLE
Uncaught TypeError: n.model.value is undefined

### ISSUE THREAD

**Issue by lahwaacz** [DerThorsten/jupyterlab_pytutor#19]
I just installed jupyterlab-pytutor-0.1.1 but clicking on the "pytutor" button in Jupyterlab does not open the side panel/window, instead it results in the following error on JavaScript console in the browser:
```
Uncaught TypeError: n.model.value is undefined
    o http://localhost:8888/lab/extensions/jupyterlab-pytutor/static/697.3cabcc8cf7d78b100378.js?v=3cabcc8cf7d78b100378:1
    o http://localhost:8888/lab/extensions/jupyterlab-pytutor/static/697.3cabcc8cf7d78b100378.js?v=3cabcc8cf7d78b100378:1
    s http://localhost:8888/static/lab/jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1
    Ue http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Qe http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    je http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    al http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    ul http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Os http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    De http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    lt http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    tt http://localhost:8888/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
697.3cabcc8cf7d78b100378.js:1:1439
```

Maybe pytutor needs to be updated for jupyterlab 4.0?

**Comment by lahwaacz** [comment]
@jtpio Any idea what is the problem here?

**Comment by jtpio** [comment]
> Maybe pytutor needs to be updated for jupyterlab 4.0?

It could be because of this yes.

Would you be able to open a draft PR to update the extension to JupyterLab 4?

We can use the upgrade script which should help do most of the update: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#upgrading-extension-using-the-upgrade-script

Thanks!

**Comment by lahwaacz** [comment]
I tried the script, but I have doubts about its option `python_name: jupyterlab-pytutor` from `.copier-answers.yml`. It also replaced `jupyterlab_pytutor` with `jupyterlab-pytutor` in `pip` commands which is obviously wrong... Nevertheless, I've put the result to https://github.com/jupyterlab-contrib/jupyterlab-pytutor/pull/20, let me know if you see something wrong.

**Comment by lahwaacz** [comment]
I got this error when running `jlpm run build` on the branch for #20, which corresponds to this issue:
```
src/index.ts:112:32 - error TS2339: Property 'value' does not exist on type 'ICellModel'.

112           src += `${cell.model.value.text}\n`;
                                   ~~~~~


Found 1 error in src/index.ts:112
```

**Comment by jtpio** [comment]
Ah yes, this is one of the breaking changes in JupyterLab 4 that needs an update.
