### ISSUE TITLE
Move to the `jupyterlab-contrib` organization?

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/jupyterlab_pytutor#3]
The `jupyterlab-contrib` org on GitHub is a good place for community extensions: https://github.com/jupyterlab-contrib

Having this repo there could help increase its visibility.

Let me know what you think @DerThorsten and I can help with the move if you would like to. The process is to create a new issue and follow the template: https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/new?labels=transfer&template=transfer-repository-to-this-organization.md

**Comment by DerThorsten** [comment]
here we go https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/38

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/38
