### ISSUE TITLE
pytutor button does not appear in binder /  extension is probably not installed

### ISSUE THREAD

**Issue by DerThorsten** [DerThorsten/jupyterlab_pytutor#6]
pytutor button does not appear in binder /  extension is probably not installed

**Comment by DerThorsten** [comment]
@jtpio any idea?

**Comment by jtpio** [comment]
First guess would be to use a more recent version of node.js: https://github.com/DerThorsten/jupyterlab_pytutor/pull/2#issuecomment-1382084347

**Comment by DerThorsten** [comment]
this should already be done (https://github.com/DerThorsten/jupyterlab_pytutor/blob/main/.binder/environment.yml)

**Comment by jtpio** [comment]
ah ok then maybe add a `postBuild` file with `python -m pip install .` in it.

**Comment by jtpio** [comment]
Let's check in https://github.com/DerThorsten/jupyterlab_pytutor/pull/9
